apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-static 
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-static
  template:
    metadata:
      labels:
        app: lms-static
    spec:
      containers:
        - name: lms-static
          image: kalharacodes/lms-static:latest
          ports:
            - containerPort: 80
          